---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  labels: 
    type: webserver
    author: raju
spec: 
  replicas: 2
  selector: 
    matchLabels:
      type: webserver
  template: 
    metadata:
      name: nginx-pod
      labels: 
        type: webserver
    spec:
      containers:
        - name: nginx
          image: nginx
          ports: 
            - containerPort: 80
              hostPort: 9090
          resources: 
            requests:
              cpu: 400m
              memory: 64M
            limits: 
              cpu: 500m
              memory: 128M 
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node1
                  operator: In
                  values:
                    - raju
...
