---
apiVersion: v1
kind: Pod
metadata: 
  name: mysql-pod
  labels: 
    app: db
    author: raju
spec: 
  containers:
    - name: mysql-pod
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: a
...
