---
apiVersion: v1
kind: Pod
metadata: 
  name: tomee-pod
  labels: 
    type: tomee
    author: raju
spec: 
  containers:
    - name: tomee-pod
      image: tomee
      ports:
        - containerPort: 8080
          hostPort: 90
  affinity:
    nodeAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: node1
              operator: In
              values: 
               - raju
...
