---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
  labels: 
    type: proxy
    author: raju
spec:
  containers: 
    - name: nginx-pod
      image: nginx
      ports: 
       - containerPort: 80
         hostPort: 8080
...
