---
apiVersion: v1
kind: Pod
metadata: 
  name: tomcat-pod
  namespace: test-ns
  labels: 
    type: production
    author: raju
spec:
  containers: 
    - name: tomcat-pod
      image: tomcat
      ports: 
        - containerPort: 8080
          hostPort: 8888
...
