---
apiVersion: v1
kind: Service
metadata: 
  name: postgres-app-service
  labels: 
    author: raju
spec: 
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector: 
    type: postgres-app
    author: raju    
  
...
