---
apiVersion: v1
kind: Service
metadata:
  name: redis-app
  labels: 
    author: raju
spec: 
  type: ClusterIP
  ports: 
    - targetPort: 6379
      port: 6379
  selector:
    type: redis-app
    author: raju

...
