---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  labels:
    author: raju
spec:
  storageClassName: standard
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 3G
...
