---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: jenkins-rc
  labels:
    type: ci-cd
    author: raju
spec:
  replicas: 3
  template:
    metadata:
      name: jenkins-pod
      labels:
        type: ci-cd
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins
          ports: 
            - containerPort: 8080
              hostPort: 4444
...
