---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: tomcat-rs
  labels: 
    type: webserver
    author: raju
spec:
  replicas: 3
  selector:
    matchLabels: 
      type: webserver
  template: 
    metadata:
      name: tomcat-pod
      labels: 
        type: webserver
    spec:
      containers:
        - name: tomcat
          image: tomcat
          ports:
            - containerPort: 8080
              hostPort: 2222
...
