---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: mysql-rs
  labels: 
    type: db
    author: raju
spec: 
  replicas: 2
  selector: 
    matchLabels:
      type: db
  template:
    metadata:
      name: mysql-pod
      labels: 
        type: db
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
              hostPort: 9090
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: raju
...
