---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
  labels: 
    type: webserver
    author: raju
spec: 
  containers:
    - name: httpd
      image: httpd
      resources:
        requests:
          cpu: 200M
          memory: 64M
        limits: 
          cpu: 500M
          memory: 128M
...
