---
apiVersion: v1
kind: Service
metadata: 
  name: nodeport-service
  labels: 
    author: raju
spec: 
  type: NodePort
  ports: 
   - targetPort: 3306
     port: 3306
     nodePort: 30008
  selector:
    app: db
    author: raju  
...
