---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql-deployment
  labels:
    type: db
    author: raju
spec:
  replicas: 2
  selector:
    matchLabels:
      type: db
  template:
    metadata: 
      name: mysql-pod
      labels: 
        type: db
    spec:
      containers:
        - name: mysql-pod
          image: mysql
          volumeMounts:
            - name: myvolume
              mountPath: /data/mysql
      volumes:
        - name: myvolume
          emptyDir: {}
...
