---
apiVersion: v1
kind: Pod
metadata: 
  name: redis-pod
  labels: 
    app: db
    author: raju
spec: 
  containers:
    - name: myredis
      image: redis
      volumeMounts: 
       - name: myvolume
         mountPath: /data/redis
  volumes: 
   - name: myvolume
     emptyDir: {} 
...
