---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    type: db
    author: raju
spec:
  containers:
    - name: mysql-pod
      image: mysql
      ports:
        - containerPort: 3306
          hostPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: raju
      volumeMounts:
        - name: myraju
          mountPath: /var/lib/mysql
  volumes:
    - name: myraju
      persistentVolumeClaim:
        claimName: my-pvc
...
