---
apiVersion: v1
kind: Service
metadata: 
  name: headless-service
  labels: 
    author: raju
spec: 
  clusterIP: None
  ports: 
   - targetPort: 80
     port: 80
  selector: 
    type: proxy
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
  labels: 
    type: proxy
spec:
  replicas: 5
  selector: 
    matchLabels: 
      type: proxy
  template: 
    metadata:
      name: nginx-pod
      labels:
        type: proxy
    spec:
      containers: 
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 80
          volumeMounts: 
            - name: nginx-volume
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata: 
        name: nginx-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests: 
            storage: 3G
...
