---
apiVersion: v1
kind: Service
metadata: 
  name: headless-service
  labels:
    type: db
spec: 
  clusterIP: None
  ports:
    - targetPort: 3306
      port: 3306
  selector: 
    type: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: mysql-statefulset
  labels: 
    type: db
    author: raju
spec:
  replicas: 3
  selector: 
    matchLabels: 
      type: db
  template: 
    metadata:
      name: mysql-pod
      labels: 
        type: db
    spec:
      containers: 
        - name: mysql
          image: mysql
          ports: 
            - containerPort: 3306
              hostPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: raju
          volumeMounts: 
            - name: mysql-volume
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata: 
        name: mysql-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources: 
          requests: 
            storage: 3G
...
